// Demo dashboard generated with tabler-mcp-server's own engines (dogfooding):
// icons come from the icon engine, the document shell from the template builder.
// Run: node examples/generate-demo.mjs  ->  writes examples/dashboard.html

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { getIconSvg } from "../dist/icons.js";
import { buildHtmlDocument } from "../dist/template.js";

const here = dirname(fileURLToPath(import.meta.url));
const icon = (name, opts = {}) => getIconSvg(name, "outline", opts).replace('class="', 'class="icon ');

const statCards = [
  { title: "Revenue", value: "$4,300", delta: "+8%", up: true, icon: "currency-dollar", color: "primary" },
  { title: "New clients", value: "6,782", delta: "+12%", up: true, icon: "users", color: "green" },
  { title: "Active projects", value: "132", delta: "-2%", up: false, icon: "briefcase", color: "yellow" },
  { title: "Uptime", value: "99.98%", delta: "+0.1%", up: true, icon: "activity-heartbeat", color: "azure" },
];

const stats = statCards
  .map(
    (s) => `
        <div class="col-sm-6 col-lg-3">
          <div class="card">
            <div class="card-body">
              <div class="d-flex align-items-center">
                <div class="subheader">${s.title}</div>
                <div class="ms-auto">
                  <span class="text-${s.up ? "green" : "red"} d-inline-flex align-items-center lh-1">
                    ${s.delta} ${icon(s.up ? "trending-up" : "trending-down", { size: 16 })}
                  </span>
                </div>
              </div>
              <div class="d-flex align-items-baseline mt-2">
                <div class="h1 mb-0 me-2">${s.value}</div>
                <span class="avatar avatar-sm bg-${s.color}-lt ms-auto">${icon(s.icon, { size: 20 })}</span>
              </div>
            </div>
          </div>
        </div>`
  )
  .join("\n");

const team = [
  { init: "MK", name: "Maya Kalinski", role: "Product Designer", badge: "bg-green-lt", status: "Active", progress: 84, color: "bg-green" },
  { init: "JD", name: "Jonas Duval", role: "Frontend Engineer", badge: "bg-blue-lt", status: "In review", progress: 62, color: "bg-blue" },
  { init: "AS", name: "Amira Saleh", role: "Data Analyst", badge: "bg-yellow-lt", status: "Pending", progress: 45, color: "bg-yellow" },
  { init: "TW", name: "Tom Weber", role: "DevOps", badge: "bg-green-lt", status: "Active", progress: 91, color: "bg-green" },
];

const rows = team
  .map(
    (m) => `
              <tr>
                <td>
                  <div class="d-flex align-items-center">
                    <span class="avatar avatar-sm me-2">${m.init}</span>
                    <div>
                      <div>${m.name}</div>
                      <div class="text-secondary">${m.role}</div>
                    </div>
                  </div>
                </td>
                <td><span class="badge ${m.badge}">${m.status}</span></td>
                <td class="w-25">
                  <div class="progress progress-sm">
                    <div class="progress-bar ${m.color}" style="width: ${m.progress}%"></div>
                  </div>
                </td>
                <td class="text-secondary">${m.progress}%</td>
              </tr>`
  )
  .join("\n");

const body = `<div class="page">
    <header class="navbar navbar-expand-md d-print-none">
      <div class="container-xl">
        <div class="navbar-brand d-flex align-items-center gap-2">
          ${icon("layout-dashboard", { size: 28, color: "var(--tblr-primary)" })}
          <span class="fw-bold">Acme Cloud</span>
        </div>
        <div class="navbar-nav flex-row order-md-last align-items-center gap-2">
          <span class="badge bg-purple-lt d-none d-md-inline">Generated by tabler-mcp-server 🤖</span>
          <span class="avatar avatar-sm bg-primary-lt">DM</span>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav">
            <li class="nav-item active"><a class="nav-link" href="#">${icon("home", { size: 18 })}<span class="nav-link-title ms-1">Home</span></a></li>
            <li class="nav-item"><a class="nav-link" href="#">${icon("chart-bar", { size: 18 })}<span class="nav-link-title ms-1">Analytics</span></a></li>
            <li class="nav-item"><a class="nav-link" href="#">${icon("settings", { size: 18 })}<span class="nav-link-title ms-1">Settings</span></a></li>
          </ul>
        </div>
      </div>
    </header>
    <div class="page-wrapper">
      <div class="page-header d-print-none">
        <div class="container-xl">
          <div class="row g-2 align-items-center">
            <div class="col">
              <div class="page-pretitle">Overview</div>
              <h2 class="page-title">Dashboard</h2>
            </div>
            <div class="col-auto ms-auto d-print-none">
              <div class="btn-list">
                <a href="#" class="btn">${icon("download", { size: 18 })} Export</a>
                <a href="#" class="btn btn-primary">${icon("plus", { size: 18 })} New report</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="page-body">
        <div class="container-xl">
          <div class="row row-deck row-cards">
${stats}
            <div class="col-lg-8">
              <div class="card">
                <div class="card-header">
                  <h3 class="card-title">Revenue overview</h3>
                  <div class="card-actions">
                    <span class="status status-green"><span class="status-dot status-dot-animated"></span> Live</span>
                  </div>
                </div>
                <div class="card-body">
                  <div id="chart-revenue" style="height: 240px"></div>
                </div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="card">
                <div class="ribbon bg-red">New</div>
                <div class="card-header"><h3 class="card-title">System status</h3></div>
                <div class="card-body">
                  <div class="mb-3">
                    <div class="d-flex mb-1"><div>API uptime</div><div class="ms-auto text-secondary">99.98%</div></div>
                    <div class="tracking">
                      ${'<div class="tracking-block bg-success"></div>'.repeat(14)}<div class="tracking-block bg-warning"></div>${'<div class="tracking-block bg-success"></div>'.repeat(5)}
                    </div>
                  </div>
                  <div class="hr-text">this week</div>
                  <div class="d-flex align-items-center mb-2">
                    <span class="avatar avatar-sm bg-green-lt me-2">${icon("check", { size: 18 })}</span>
                    <div>Deployment <strong>v2.4</strong> succeeded</div>
                    <div class="ms-auto text-secondary">2h</div>
                  </div>
                  <div class="d-flex align-items-center">
                    <span class="avatar avatar-sm bg-yellow-lt me-2">${icon("alert-triangle", { size: 18 })}</span>
                    <div>Disk usage above <strong>80%</strong></div>
                    <div class="ms-auto text-secondary">6h</div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <h3 class="card-title">Team activity</h3>
                  <div class="card-actions"><a href="#" class="btn btn-sm">View all</a></div>
                </div>
                <div class="table-responsive">
                  <table class="table table-vcenter card-table">
                    <thead><tr><th>Member</th><th>Status</th><th colspan="2">Sprint progress</th></tr></thead>
                    <tbody>
${rows}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer footer-transparent d-print-none">
        <div class="container-xl">
          <div class="row text-center align-items-center">
            <div class="col">
              Built with <a href="https://tabler.io" target="_blank" rel="noopener">Tabler</a> ·
              generated by <a href="https://github.com/MaFady/tabler-mcp-server" target="_blank" rel="noopener">tabler-mcp-server</a> ·
              Mafady AI Studio — Supervised by Dr Maher
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/apexcharts@4.7.0/dist/apexcharts.min.js" integrity="sha384-Hf0cGsweCbozkRP14s5KIue6STJYKaoipB/i1gTdbX+umKD59qA/Szk42FPMuKtB" crossorigin="anonymous"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      new ApexCharts(document.getElementById("chart-revenue"), {
        chart: { type: "area", height: 240, toolbar: { show: false }, fontFamily: "inherit" },
        series: [
          { name: "Revenue", data: [28, 34, 33, 42, 38, 48, 52, 47, 58, 64, 60, 72] },
          { name: "Expenses", data: [18, 22, 24, 26, 25, 30, 32, 30, 34, 38, 36, 41] },
        ],
        stroke: { width: 2, curve: "smooth" },
        fill: { type: "gradient", gradient: { opacityFrom: 0.35, opacityTo: 0.05 } },
        colors: ["var(--tblr-primary)", "var(--tblr-green)"],
        grid: { strokeDashArray: 4 },
        dataLabels: { enabled: false },
        xaxis: { categories: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"], axisBorder: { show: false } },
        legend: { show: true, position: "bottom" },
      }).render();
    });
  </script>`;

const html = buildHtmlDocument(body, { title: "Acme Cloud — Dashboard" });
const out = join(here, "dashboard.html");
writeFileSync(out, html);
console.log("Demo written to", out);
