/** Full HTML document builder for layouts and starter templates. */

import { CDN, TABLER_VERSION } from "./version.js";

export interface DocumentOptions {
  title?: string;
  /** "light" | "dark" */
  theme?: string;
  /** Extra plugin stylesheets: flags, payments, socials, vendors. */
  plugins?: string[];
  /** Include the Tabler Icons webfont stylesheet. */
  iconsWebfont?: boolean;
}

const PLUGIN_CSS: Record<string, string> = {
  flags: CDN.flagsCss,
  payments: CDN.paymentsCss,
  socials: CDN.socialsCss,
  vendors: CDN.vendorsCss,
};

export function buildHtmlDocument(body: string, opts: DocumentOptions = {}): string {
  const title = opts.title?.trim() || "Tabler App";
  const themeAttr = opts.theme === "dark" ? ' data-bs-theme="dark"' : "";

  const extraCss: string[] = [];
  for (const p of opts.plugins ?? []) {
    const href = PLUGIN_CSS[p.toLowerCase()];
    if (href) extraCss.push(`    <link rel="stylesheet" href="${href}" />`);
  }
  if (opts.iconsWebfont) {
    extraCss.push(`    <link rel="stylesheet" href="${CDN.iconsWebfontCss}" />`);
  }

  const filledBody = body.replace(/\{\{TITLE\}\}/g, escapeHtml(title));

  return `<!doctype html>
<!-- Built with Tabler ${TABLER_VERSION} (https://tabler.io) — generated by tabler-mcp-server -->
<html lang="en"${themeAttr}>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <title>${escapeHtml(title)}</title>
    <link rel="stylesheet" href="${CDN.css}" />
${extraCss.length ? extraCss.join("\n") + "\n" : ""}  </head>
  <body>
    <!-- For production, consider adding Subresource Integrity (integrity + crossorigin) to CDN tags. -->
    ${filledBody}
    <script src="${CDN.js}" defer></script>
  </body>
</html>
`;
}

export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
